### ISSUE TITLE
推荐被 awesome-avalonia 收录

### ISSUE THREAD

**Issue by lindexi** [zxyao145/XmlyDownloader#1]
有趣的项目，是否可以加入到 https://github.com/AvaloniaCommunity/awesome-avalonia 收录

**Comment by zxyao145** [comment]
感谢大佬，直接提 PR 吗？

**Comment by lindexi** [comment]
@zxyao145  我也不知道，只是看到 https://github.com/AvaloniaCommunity/awesome-avalonia 这个官方项目

**Comment by zxyao145** [comment]
好的，谢谢大佬！
